version: '3'
services:
  myapplication:
    image: amyth18/maximus:1.0
    container_name: maximus
    environment: 
      - MONGO_CONN_STRING=mongodb://mongodb:27017
      - MAX_EMAILS=1000
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
